# Generated by Django 4.2.11 on 2024-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('car_type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('lpg', 'lpg'), ('electric', 'electric')], max_length=255)),
            ],
        ),
    ]
